@startuml Question 4: Examples

skinparam {
    backgroundColor white
}

bed <|---* "1..*" pillow

bed <|--* "1..3" sheet

bed <|---* "0..1" comforter

bed <|--* "1" mattress

bed <|---* "0..1" boxSpring

@enduml




' Use Alt + D to open PUML Preview