@startuml

class order {
    keepHistory()
}
class client {
    collectData()
}
CEO "1" - "*" portfolioManager
portfolioManager "1..3" - "1" portfolio
portfolio "*" -- "*" asset
client "*" - "*" asset
(client, asset) .. order
order <|-- buy
order <|-- sell
data -- order: < sendData
data . client : < sendData
asset <|-- "*" stocks
asset <|-- "*" mutualFunds
asset <|-- "*" cash

@enduml